trigger:
- master

pool:
  name: 'personal'  # 👈 This tells Azure to use your self-hosted agent

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
